### ISSUE TITLE
last_run_time.json

### ISSUE THREAD

**Issue by mcushing** [omriasta/ifitsync#1]
I get both the iFit and Google Fit authentication working and then I get this error. I hope maybe I'm missing something. I tried creating empty 'last_run_time.json' file but that did not work.
`
Traceback (most recent call last):
  File "ifitsync.py", line 674, in <module>
    with open('last_run_time.json') as timestamp_file:
FileNotFoundError: [Errno 2] No such file or directory: 'last_run_time.json'
`

**Comment by omriasta** [comment]
Yep, my bad, it doesn't check if the file exists for the first run. I'll fix it tomorrow morning. It's just a file that shows the last time you ran the script.

**Comment by omriasta** [comment]
OK, this is fixed in my last commit. It will check if the file exists first, if it does not, it will upload everything that is returned (last 5 workouts or entire history, depending on the URL you select in get_ifitaccount.py). If the file exists it will just upload anything added since last run time. Can you test and let me know?

**Comment by mcushing** [comment]
Thank you, that has resolved my issues! Awesome job on the script.

**Comment by omriasta** [comment]
Thanks, glad it's working!
